#!/bin/sh
# One can set IMPORT_HOME_DIR as an environmental variable and we'll use
# that.  Otherwise, we'll guess it off of where we were called from.

if [ x$IMPORT_HOME_DIR = 'x' ]; then
    IMPORT_HOME_DIR=`dirname $0`/..
fi

IMPORT_LIB_DIR=$IMPORT_HOME_DIR/lib
CLASSPATH=$IMPORT_HOME_DIR/classes

for i in $IMPORT_LIB_DIR/*.jar
do
    CLASSPATH=$i:$CLASSPATH
done

# Uncomment to allow remote debugging
#DEBUG="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"

export LD_LIBRARY_PATH=${IMPORT_LIB_DIR}

java $DEBUG -cp $CLASSPATH org.realtors.rets.server.admin.Main $*
