ln source/outside.jpg 1_1.jpg
ln source/dining_room.jpg 1_2.jpg
ln source/family_room.jpg 1_3.jpg
ln source/great_room.jpg 1_4.jpg
ln source/library.jpg 2_1.jpg
ln source/large_image.jpg 2_2.jpg
ln source/living_room.jpg 3_1.jpg
ln source/porch.jpg 4_1.jpg
ln source/outside.jpg 5_1.jpg
