--
-- Data for Object [dbo].[actagt]
--

INSERT INTO actagt (office_id, agent_id, r_md) VALUES ('','agent07','')
INSERT INTO actagt (office_id, agent_id, r_md) VALUES ('','Joe','')
GO

--
-- Data for Object [dbo].[agt]
--

INSERT INTO agt (cell_phone, office_id, first_name, agent_id, last_name, dsgnations, url, off_phone, password, r_md) VALUES ('8005882300','','James','agent07','Bond','','http://realtor.org/crt','','password','')
INSERT INTO agt (cell_phone, office_id, first_name, agent_id, last_name, dsgnations, url, off_phone, password, r_md) VALUES ('8675309','','Joe','Joe','Schmoe','','http://realtor.org/crt','','password','')
GO

--
-- Data for Object [dbo].[rets_user]
--

SET IDENTITY_INSERT [dbo].[rets_user] ON
GO

INSERT INTO rets_user (id, firstname, lastname, username, passwordmethod, password, agentcode, brokercode) VALUES ('1','Joe','Schmoe','Joe','A1:RETS Server','a04aab7e749c8f532b78bdd61dfa0cb2','','')
GO

SET IDENTITY_INSERT [dbo].[rets_user] OFF
GO

--
-- Data for Object [dbo].[rets_group]
--

SET IDENTITY_INSERT [dbo].[rets_group] ON
GO

INSERT INTO rets_group (id, name, description) VALUES ('3','users','General Users')

SET IDENTITY_INSERT [dbo].[rets_group] OFF
GO

--
-- Data for Object [dbo].[rets_user_groups]
--

INSERT INTO rets_user_groups (group_id, user_id) VALUES ('3','1')
GO

--
-- Data for Object [dbo].[rets_accounting]
--

SET IDENTITY_INSERT [dbo].[rets_accounting] ON
GO

INSERT INTO rets_accounting (id, totaltime, userid) VALUES ('2','28369221','1')
GO

SET IDENTITY_INSERT [dbo].[rets_accounting] OFF
GO

--
-- Data for Object [dbo].[rets_property_res]
--

INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000005','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000003','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000004','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000002','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000001','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000006','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000007','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000008','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000009','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000010','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000011','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000012','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000013','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000014','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000015','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000016','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000017','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000018','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000019','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000020','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000021','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000022','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000023','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000024','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000025','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000026','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000027','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000028','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000029','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000030','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000031','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000032','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000033','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000034','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000035','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000036','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000037','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000038','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000039','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000040','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000041','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000042','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000043','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000044','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000045','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-04-14','','300000','2','5','agent07','Chicago','Cook','LN000046','','60605','IL','430','N','Michigan Ave','','','','','','','Active','1','1400','11','1989','1250.1199999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2005-03-23','','250000','1','3','Joe','Chicago','Cook','LN000047','','60613','IL','1250','E','Armitage Ave','','','','','','','Active','3','900','8','1975','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-04-01','','425000','3','5','agent07','Evanston','Cook','LN000048','','60533','IL','120','','Main St','','','','','','','Active','','','','1922','10.000999999999999','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-05-30','','380000','3','4','Joe','Buffalo Grove','Lake','LN000049','','60089','IL','83','','Fox Hill','','','','','','','Active','','','','1985','','','','','')
INSERT INTO rets_property_res (r_ld, r_md, r_lp, r_baths, r_beds, r_agent_id, r_city, r_county, r_ln, r_office_id, r_zip_code, r_state, r_stnum, r_street_dir_prefix, r_stname, r_ltyp, r_board, r_cldate, r_codate, r_cp, r_unnum, r_ls, r_garage, r_area, r_rooms, r_year_built, r_sqft, r_thumb_md, r_thumbnails, r_photo_md, r_photos)
VALUES ('2004-07-04','','250000','3','4','agent07','Chicago','Cook','LN000050','','60605','IL','625','N','Michigan','','','2004-09-01','','233000','','Closed','2','1100','9','1978','1500.2322999999999','','','','')

--
-- Data for Object [dbo].[xceligent]
--

INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('585893','SEC of Randolph and Lexington','SE of Randolph and Lexington','1','Saint Paul','MN','Ramsey','55105','Minneapolis-St. Paul','Ret','26571','26571','26571','26571','1','Existing','A','NULL','Exclusive','50:05.2','10:06.4','Active','N','14341','Amy','Senn','asenn@welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Gas Station/Conv Store','Single-Tenant','$875,000','(952) 897-7833','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('573687','Gander Mountain Outlots','SE of I-94 and Woodbury Dr','1','Woodbury','MN','Washington','55125','Minneapolis-St. Paul','Ret','85000','85000','85000','85000','1','Proposed','A','NULL','Exclusive','41:26.7','52:08.7','Active','N','13898','Chris','Simmons','csimmons@Welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Freestanding','Multi-Tenant','$3,045,715','(952) 897-7760','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('471812','Former Burger King','7516 Brooklyn Blvd','1','Brooklyn Park','MN','Hennepin','55443','Minneapolis-St. Paul','Ret','3500','3500','3500','3500','NULL','Existing','A','1974','Exclusive','26:30.8','52:08.6','Active','N','13898','Chris','Simmons','csimmons@Welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Fast Food','Single-Tenant','$495,000','(952) 897-7760','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('490371','Diamond Lake Fast Lube & Car Wash','21025 Diamond Lake Rd S','1','Rogers','MN','Hennepin','55374','Minneapolis-St. Paul','Ret','5335','5335','5335','5335','NULL','Existing','A','2001','Exclusive','02:30.6','54:17.9','Active','N','13841','Jeff','Minea','jminea@welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Automotive','Single-Tenant','$1,150,000','(952) 897-7741','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('531067','Former Burger King','8097 Hwy 65','1','Spring Lake Park','MN','Anoka','55432','Minneapolis-St. Paul','Ret','2757','2757','2757','2757','NULL','Existing','A','NULL','Exclusive','37:30.9','52:08.6','Active','N','13898','Chris','Simmons','csimmons@Welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Fast Food','','$650,000','(952) 897-7760','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('586197','11700 JeffersonSt NE','11700 JeffersonSt NE','1','Blaine','MN','Anoka','55434','Minneapolis-St. Paul','Ret','8010','8010','8010','8010','1','Existing','A','NULL','Exclusive','27:08.8','20:50.3','Active','N','17173','Eric','Batiza','ebatiza@welshco.com','NAI Welsh Commercial Real Estate Services','900 2nd Ave S #200','Minneapolis','MN','55402','Neighborhood Ctr','Multi-Tenant','$600,000','(952) 837-3007','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('179249','Audio King Building','5939 John Martin Dr','1','Brooklyn Center','MN','Hennepin','55430-2509','Minneapolis-St. Paul','Ret','15000','15000','15000','15000','1','Existing','A','1984','Exclusive','44:14.2','52:08.7','Active','N','13682','Dan','Brastad, CCIM','dbrastad@welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Freestanding','Single-Tenant','$1,750,000','(952) 897-7890','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('456359','2510 Kenzie Terr','2510 Kenzie Terr','1','Minneapolis','MN','Hennepin','55418','Minneapolis-St. Paul','Ret','NULL','5866','NULL','5866','1','Existing','A','NULL','Exclusive','17:37.3','24:37.0','Active','N','14341','Amy','Senn','asenn@welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','General','Multi-Tenant','$599,000','(952) 897-7833','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('212638','Amoco Surplus Building','6300 Lakeland Ave N','1','Brooklyn Park','MN','Hennepin','55428','Minneapolis-St. Paul','Ret','1540','1540','1540','1540','1','Existing','A','1968','Exclusive','12:51.8','52:08.6','Active','N','13914','Tony','Strauss, CCIM','astrauss@welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Freestanding','Single-Tenant','$250,000','(952) 897-7882','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('177398','Levitz Furniture Building','7007 Lakeland Ave N','1','Brooklyn Park','MN','Hennepin','55428','Minneapolis-St. Paul','Ret','50309','50309','50309','50309','1','Existing','A','1989','Exclusive','04:59.4','48:32.2','Active','N','13874','Tim','Prinsen','tprinsen@welshco.com','NAI Welsh Commercial Real Estate Services','7807 Creekridge Circle','Minneapolis','MN','55439','Big Box','Single-Tenant','$6,075,000','(952) 897-7748','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('118674','5233-5235 S 27th St','5233-5235 S 27th St','1','Milwaukee','WI','Milwaukee','53221','Wisconsin','Ret','9860','9860','9860','9860','1','Existing','A','1984','Exclusive','23:08.4','54:25.1','Active','N','9015','Tom','Kohl','tkohl@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Conv/Strip Ctr','Multi-Tenant','$1,000,000','(414) 203-3015','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('171126','Brahm' + CHAR(39) + 's Service','725 E Geneva St','1','Delavan','WI','Walworth','53115','Wisconsin','Ret','NULL','3960','NULL','3960','1','Existing','A','NULL','Exclusive','46:20.1','48:02.2','Active','N','9022','Don','Silvers','dsilvers@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Other','Single-Tenant','$375,000','(414) 203-3035','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('167259','11042-11074 N Pilgrim (W156) Rd','11042-11074 N Pilgrim Rd','1','Germantown','WI','Washington','53022','Wisconsin','Ret','NULL','14237','NULL','14237','1','Existing','A','NULL','Exclusive','43:04.3','48:02.1','Active','N','9015','Tom','Kohl','tkohl@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Neighborhood Ctr','Multi-Tenant','$250,000','(414) 203-3015','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('574458','11201 N Port Washington Rd','11201 N Port Washington Rd','1','Mequon','WI','Ozaukee','53092','Wisconsin','Ret','1700','1700','1700','1700','1','Existing','A','NULL','Exclusive','27:55.4','01:44.8','Pending','N','9015','Tom','Kohl','tkohl@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Fast Food','Single-Tenant','$1,100,000','(414) 203-3015','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('539623','1408 Summit Ave','1408 Summit Ave','1','Oconomowoc','WI','Waukesha','53066','Wisconsin','Ret','91651','91651','91651','91651','1','Existing','A','NULL','Exclusive','28:51.9','48:02.1','Active','N','9025','Andy','Fishler','afishler@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Conv/Strip Ctr','Multi-Tenant','$10,700,000','(414) 203-3027','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('111492','532-534 N Water St','532-534 N Water St','1','Milwaukee','WI','Milwaukee','53202','Wisconsin','Ret','16800','16800','16800','16800','4','Existing','A','1870','Exclusive','17:05.6','48:02.1','Active','N','113971','Jason','Frederick','jfrederick@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Other','Multi-Tenant','$420,000','(414) 203-3031','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('113032','Milwaukee Electric Tool Tech. Center','4085 N 128th St','1','Brookfield','WI','Waukesha','53005','Wisconsin','Ind','48000','48000','48000','48000','2','Existing','A','NULL','Exclusive','37:54.1','48:01.8','Active','N','9007','James','Babiasz','jbabiasz@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Light Manufacturing','Single-Tenant','$1,800,000','(414) 203-3039','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('350685','325 E 15th St','325 E 15th St','1','Clintonville','WI','Waupaca','54929','Wisconsin','Ind','59742','NULL','NULL','59742','NULL','Existing','A','NULL','Exclusive','58:15.6','48:01.8','Active','N','9023','Chad','Vande Zande','cvandezande@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','','','$995,000','(414) 203-3024','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('110778','5023 N 35th St','5023 N 35th St','1','Milwaukee','WI','Milwaukee','53209','Wisconsin','Ind','233850','233850','233850','233850','2','Existing','A','1890','Exclusive','01:32.6','48:01.8','Active','N','9007','James','Babiasz','jbabiasz@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Flex/R&D','Multi-Tenant','$2,600,000','(414) 203-3039','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('491641','P.H. Glatfelter Facility','1655 Bergstrom Rd','1','Neenah','WI','Winnebago','54956','Wisconsin','Ind','179272','179272','179272','179272','1','Existing','A','NULL','Exclusive','34:24.9','48:01.8','Active','N','9007','James','Babiasz','jbabiasz@boerke.com','Grubb & Ellis | Boerke Company','411 E Wisconsin Ave','Milwaukee','WI','53202','Warehouse - Distribution','Single-Tenant','$2,900,000','(414) 203-3039','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('540313','7700 W 44th Ave','7700 W 44th Ave','1','Wheat Ridge','CO','Jefferson','80033','Denver','Ret','24700','24700','24700','24700','1','Existing','A','1977','Exclusive','43:15.6','14:00.2','Pending','N','100882','Greg','Knott','gknott@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Freestanding','Single-Tenant','$775,000','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('489228','2709 S Broadway','2709 S Broadway St','1','Englewood','CO','Arapahoe','80113','Denver','Ret','4088','4088','4088','4088','1','U/C','A','NULL','Exclusive','35:50.8','11:37.2','Active','N','100877','Todd','Silverman','tsilverman@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','General','Multi-Tenant','$204,400 - $817,600','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('491971','33355 Colfax Ave','33355 Colfax Ave','1','Watkins','CO','Adams','80137','Denver','Ret','7488','7488','7488','7488','1','Existing','A','NULL','Exclusive','35:47.9','20:17.6','Active','N','100875','Allen','Freedberg','afreedberg@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Restaurant','Single-Tenant','$1,925,000','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('485254','Chatfield Autobody','8537 S Reed St','1','Littleton','CO','Jefferson','80128','Denver','Ret','4608','4608','4608','4608','1','Existing','A','1979','Exclusive','48:21.5','38:22.6','Active','N','100877','Todd','Silverman','tsilverman@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Automotive','Multi-Tenant','$850,000','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('512641','310 N Wilcox St','310 N Wilcox St','1','Castle Rock','CO','Douglas','80104','Denver','Ret','5122','5122','5122','5122','1','Existing','A','NULL','Exclusive','49:10.1','17:05.9','Active','N','100874','Marc','Lippitt','mlippitt@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Restaurant','','$650,000','(303) 321-5888 Ext 201','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('417944','6161 E 88th Ave','6161 E 88th Ave','1','Henderson','CO','Adams','80640','Denver','Ind','14788','14788','14788','14788','1','Existing','A','1959','Exclusive','02:08.6','39:05.0','Active','N','100882','Greg','Knott','gknott@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Light Manufacturing','Single-Tenant','$1,100,000','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('403785','800-810 W 8th Ave','800-810 W 8th Ave','1','Denver','CO','Denver','80204','Denver','Ind','20732','20732','20732','20732','2','Existing','A','1970','Exclusive','11:44.6','04:27.5','Active','N','113692','Jules','Hochman','jbhochman@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Light Manufacturing','Single-Tenant','$2,200,000','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('374503','Discount Windows Building','4321 Broadway St','1','Denver','CO','Denver','80216','Denver','Ind','27460','27460','27460','27460','1','Existing','A','1978','Exclusive','02:47.0','01:42.3','Active','N','100882','Greg','Knott','gknott@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Light Manufacturing','Multi-Tenant','$2,325,000','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('471405','Compton Square','530 Compton St','1','Broomfield','CO','Broomfield','80020-1635','Denver','Ind','21248','NULL','NULL','21248','1','Existing','B','1990','Exclusive','46:23.4','12:03.8','Active','N','100872','Dwaine','Ulrich','dulrich@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Flex/R&D','Single-Tenant','$1,600,000','(303) 321-5888','')
INSERT INTO xceligent (property_id, property_name, address, building_number, city, state, county, zip, metro, general_use, gba, gla, nra, building_size, no_of_floors, construction_status, construction_class, year_built, listing_type, sale_created_date, sale_modified_date, sale_listing_status, sale_sharing_level, sale_agent_id, sale_agent_first_name, sale_agent_last_name, sale_email_address, sale_company_name, sale_agent_address, sale_agent_city, sale_agent_state, sale_agent_zip, specific_use, tenancy_type, sale_asking_price, sale_agent_phone_number, r_md)
VALUES ('373142','7476 S Eagle St','7476 S Eagle St','1','Englewood','CO','Arapahoe','80112','Denver','Ind','20092','20092','20092','20092','1','Existing','','1984','Exclusive','02:43.3','12:03.8','Active','N','100872','Dwaine','Ulrich','dulrich@uniqueprop.com','Unique Properties LLC','1873 South Bellaire St.','Denver','CO','80222','Warehouse - Distribution','Multi-Tenant','$1,495,000','(303) 321-5888','')

